"""game table

Revision ID: 18fd03111c07
Revises: 
Create Date: 2020-11-07 01:51:41.199555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fd03111c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=64), nullable=True),
    sa.Column('player1', sa.String(length=64), nullable=True),
    sa.Column('player2', sa.String(length=64), nullable=True),
    sa.Column('fields', sa.String(length=64), nullable=True),
    sa.Column('last_push', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_fields'), 'game', ['fields'], unique=False)
    op.create_index(op.f('ix_game_game_id'), 'game', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_last_push'), 'game', ['last_push'], unique=False)
    op.create_index(op.f('ix_game_player1'), 'game', ['player1'], unique=False)
    op.create_index(op.f('ix_game_player2'), 'game', ['player2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_player2'), table_name='game')
    op.drop_index(op.f('ix_game_player1'), table_name='game')
    op.drop_index(op.f('ix_game_last_push'), table_name='game')
    op.drop_index(op.f('ix_game_game_id'), table_name='game')
    op.drop_index(op.f('ix_game_fields'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
